// Code generated by goctl. DO NOT EDIT.
package types

type UploadResponse struct {
	UserID   int64  `json:"userId"`
	FileName string `json:"fileName"`
	FileHash string `json:"fileHash"`
	FileSize int64  `json:"fileSize"`
}

type FastUploadReq struct {
	FileName string `json:"fileName"`
	FileHash string `json:"fileHash"`
}

type MultipartUploadInitReq struct {
	FileHash string `json:"fileHash"`
	FileSize int64  `json:"fileSize"`
}

type MultipartUploadInitRes struct {
	FileHash   string `json:"fileHash"`
	FileSize   int64  `json:"fileSize"`
	UploadID   string `json:"uploadId"`
	ChunkSize  int64  `json:"chunkSize"`
	ChunkCount int64  `json:"chunkCount"`
}

type MultipartUploadReq struct {
	UploadId   string `json:"uploadId"`
	ChunkIndex string `json:"chunkIndex"`
}

type MultipartUploadMergeReq struct {
	FileHash string `json:"fileHash"`
	FileName string `json:"fileName"`
	FileSize int64  `json:"fileSize"`
	UploadID string `json:"uploadId"`
}
