// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"fs-sys/service/upload/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: FileUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/fast_upload",
				Handler: FileFastUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/multipart/init",
				Handler: FileMultipartInitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/multipart/upload",
				Handler: FileMultipartUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/multipart/merge",
				Handler: FileMultipartMergeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
