// Code generated by goctl. DO NOT EDIT!
// Source: upload.proto

package upload

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Upload interface {
		//  FileUpload 文件上传
		FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error)
	}

	defaultUpload struct {
		cli zrpc.Client
	}
)

func NewUpload(cli zrpc.Client) Upload {
	return &defaultUpload{
		cli: cli,
	}
}

//  FileUpload 文件上传
func (m *defaultUpload) FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error) {
	client := NewUploadClient(m.cli.Conn())
	return client.FileUpload(ctx, in, opts...)
}
