// Code generated by goctl. DO NOT EDIT!
// Source: upload.proto

package server

import (
	"context"

	"fs-sys/service/upload/rpc/internal/logic"
	"fs-sys/service/upload/rpc/internal/svc"
	"fs-sys/service/upload/rpc/upload"
)

type UploadServer struct {
	svcCtx *svc.ServiceContext
	upload.UnimplementedUploadServer
}

func NewUploadServer(svcCtx *svc.ServiceContext) *UploadServer {
	return &UploadServer{
		svcCtx: svcCtx,
	}
}

//  FileUpload 文件上传
func (s *UploadServer) FileUpload(ctx context.Context, in *upload.FileUploadRequest) (*upload.FileUploadResponse, error) {
	l := logic.NewFileUploadLogic(ctx, s.svcCtx)
	return l.FileUpload(in)
}
