// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tblFileFieldNames          = builder.RawFieldNames(&TblFile{})
	tblFileRows                = strings.Join(tblFileFieldNames, ",")
	tblFileRowsExpectAutoSet   = strings.Join(stringx.Remove(tblFileFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	tblFileRowsWithPlaceHolder = strings.Join(stringx.Remove(tblFileFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheTblFileIdPrefix       = "cache:tblFile:id:"
	cacheTblFileFileHashPrefix = "cache:tblFile:fileHash:"
)

type (
	tblFileModel interface {
		Insert(ctx context.Context, data *TblFile) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TblFile, error)
		FindOneByFileHash(ctx context.Context, fileHash string) (*TblFile, error)
		Update(ctx context.Context, data *TblFile) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTblFileModel struct {
		sqlc.CachedConn
		table string
	}

	TblFile struct {
		Id         int64     `db:"id"`
		FileHash   string    `db:"file_hash"` // 文件hash
		FileName   string    `db:"file_name"` // 文件名
		FileSize   int64     `db:"file_size"` // 文件大小
		FileAddr   string    `db:"file_addr"` // 文件存储位置
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		Status     int64     `db:"status"` // 状态(可用/禁用/已删除等状态)
	}
)

func newTblFileModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTblFileModel {
	return &defaultTblFileModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`tbl_file`",
	}
}

func (m *defaultTblFileModel) Insert(ctx context.Context, data *TblFile) (sql.Result, error) {
	tblFileIdKey := fmt.Sprintf("%s%v", cacheTblFileIdPrefix, data.Id)
	tblFileFileHashKey := fmt.Sprintf("%s%v", cacheTblFileFileHashPrefix, data.FileHash)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, tblFileRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FileHash, data.FileName, data.FileSize, data.FileAddr, data.Status)
	}, tblFileIdKey, tblFileFileHashKey)
	return ret, err
}

func (m *defaultTblFileModel) FindOne(ctx context.Context, id int64) (*TblFile, error) {
	tblFileIdKey := fmt.Sprintf("%s%v", cacheTblFileIdPrefix, id)
	var resp TblFile
	err := m.QueryRowCtx(ctx, &resp, tblFileIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tblFileRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTblFileModel) FindOneByFileHash(ctx context.Context, fileHash string) (*TblFile, error) {
	tblFileFileHashKey := fmt.Sprintf("%s%v", cacheTblFileFileHashPrefix, fileHash)
	var resp TblFile
	err := m.QueryRowIndexCtx(ctx, &resp, tblFileFileHashKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `file_hash` = ? limit 1", tblFileRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, fileHash); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTblFileModel) Update(ctx context.Context, data *TblFile) error {
	tblFileIdKey := fmt.Sprintf("%s%v", cacheTblFileIdPrefix, data.Id)
	tblFileFileHashKey := fmt.Sprintf("%s%v", cacheTblFileFileHashPrefix, data.FileHash)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tblFileRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FileHash, data.FileName, data.FileSize, data.FileAddr, data.Status, data.Id)
	}, tblFileIdKey, tblFileFileHashKey)
	return err
}

func (m *defaultTblFileModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	tblFileFileHashKey := fmt.Sprintf("%s%v", cacheTblFileFileHashPrefix, data.FileHash)
	tblFileIdKey := fmt.Sprintf("%s%v", cacheTblFileIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tblFileIdKey, tblFileFileHashKey)
	return err
}

func (m *defaultTblFileModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheTblFileIdPrefix, primary)
}

func (m *defaultTblFileModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tblFileRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTblFileModel) tableName() string {
	return m.table
}
