// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResonse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Username string `json:"username"` // 用户名
	Mobile   string `json:"mobile"`   // 用户电话
	Password string `json:"password"`
}

type UserInfoResponse struct {
	ID         int64  `json:"id"`
	Username   string `json:"username"` // 用户名
	Mobile     string `json:"mobile"`   // 用户电话
	CreateTime int64  `json:"create_time"`
	UpdateTime int64  `json:"update_time"`
}
